
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ERROR_IDENTIFICADOR = 57;
  public static final int OPERADOR_CORCHETE_ABRIR = 19;
  public static final int CHAR = 53;
  public static final int OPERADOR_MULTIPLICACION = 15;
  public static final int OPERADOR_MENOR_QUE = 9;
  public static final int OPERADOR_BOOLEANO = 61;
  public static final int REPEAT = 47;
  public static final int INT = 50;
  public static final int WRITE = 46;
  public static final int OPERADOR_SUSTRACCION = 14;
  public static final int STATIC = 44;
  public static final int OPERADOR_MAYOR_OPERADOR_ASIGNACION_QUE = 5;
  public static final int OPERADOR_LLAVE_ABRIR = 21;
  public static final int IDENTIFICADOR = 38;
  public static final int OPERADOR_DIVISION = 16;
  public static final int OPERADOR_MENOR_OPERADOR_ASIGNACION_QUE = 8;
  public static final int OPERADOR_ASIGNACION_DIVISION = 28;
  public static final int OPERADOR_DIFERENTE_DE = 24;
  public static final int OPERADOR_LLAVE_CERRAR = 22;
  public static final int OPERADOR_ASIGNACION_SUSTRACCION = 26;
  public static final int CLASS = 37;
  public static final int OPERADOR_DOS_PUNTOS = 31;
  public static final int LITERAL_NUM_ENTERO = 41;
  public static final int OPERADOR_DISMINUCION = 4;
  public static final int MAIN = 36;
  public static final int BOOLEAN = 55;
  public static final int EOF = 0;
  public static final int TRUE = 48;
  public static final int OPERADOR_PARENTESIS_ABRIR = 17;
  public static final int COMILLAS = 32;
  public static final int PALABRA = 12;
  public static final int error = 1;
  public static final int OPERADOR_PARENTESIS_CERRAR = 18;
  public static final int CADENA = 11;
  public static final int OPERADOR_MAYOR_IGUAL_QUE = 7;
  public static final int PALABRA_RESERVADA = 39;
  public static final int TIPO_DATO = 33;
  public static final int OPERADOR_LOGICO = 34;
  public static final int OPERADOR_INCREMENTO = 3;
  public static final int REAL = 56;
  public static final int ERROR_PALABRA_RESERVADA = 59;
  public static final int SHORTINT = 52;
  public static final int OPERADOR_ASIGNACION_ADICION = 25;
  public static final int ERROR_OPERADOR = 58;
  public static final int OPERADOR_RELACIONAL = 35;
  public static final int OPERADOR_COMA = 29;
  public static final int OPERADOR = 2;
  public static final int READ = 45;
  public static final int LITERAL_STRING = 40;
  public static final int FINAL = 43;
  public static final int OPERADOR_MENOR_IGUAL_QUE = 10;
  public static final int ERROR_LITERAL = 60;
  public static final int STRING = 54;
  public static final int OPERADOR_ADICION = 13;
  public static final int OPERADOR_ASIGNACION = 23;
  public static final int OPERADOR_MAYOR_QUE = 6;
  public static final int FALSE = 49;
  public static final int TERMINADOR = 30;
  public static final int OPERADOR_CORCHETE_CERRAR = 20;
  public static final int LONGINT = 51;
  public static final int OPERADOR_ASIGNACION_MULTIPLICACION = 27;
  public static final int LITERAL_NUM_FLOTANTE = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPERADOR",
  "OPERADOR_INCREMENTO",
  "OPERADOR_DISMINUCION",
  "OPERADOR_MAYOR_OPERADOR_ASIGNACION_QUE",
  "OPERADOR_MAYOR_QUE",
  "OPERADOR_MAYOR_IGUAL_QUE",
  "OPERADOR_MENOR_OPERADOR_ASIGNACION_QUE",
  "OPERADOR_MENOR_QUE",
  "OPERADOR_MENOR_IGUAL_QUE",
  "CADENA",
  "PALABRA",
  "OPERADOR_ADICION",
  "OPERADOR_SUSTRACCION",
  "OPERADOR_MULTIPLICACION",
  "OPERADOR_DIVISION",
  "OPERADOR_PARENTESIS_ABRIR",
  "OPERADOR_PARENTESIS_CERRAR",
  "OPERADOR_CORCHETE_ABRIR",
  "OPERADOR_CORCHETE_CERRAR",
  "OPERADOR_LLAVE_ABRIR",
  "OPERADOR_LLAVE_CERRAR",
  "OPERADOR_ASIGNACION",
  "OPERADOR_DIFERENTE_DE",
  "OPERADOR_ASIGNACION_ADICION",
  "OPERADOR_ASIGNACION_SUSTRACCION",
  "OPERADOR_ASIGNACION_MULTIPLICACION",
  "OPERADOR_ASIGNACION_DIVISION",
  "OPERADOR_COMA",
  "TERMINADOR",
  "OPERADOR_DOS_PUNTOS",
  "COMILLAS",
  "TIPO_DATO",
  "OPERADOR_LOGICO",
  "OPERADOR_RELACIONAL",
  "MAIN",
  "CLASS",
  "IDENTIFICADOR",
  "PALABRA_RESERVADA",
  "LITERAL_STRING",
  "LITERAL_NUM_ENTERO",
  "LITERAL_NUM_FLOTANTE",
  "FINAL",
  "STATIC",
  "READ",
  "WRITE",
  "REPEAT",
  "TRUE",
  "FALSE",
  "INT",
  "LONGINT",
  "SHORTINT",
  "CHAR",
  "STRING",
  "BOOLEAN",
  "REAL",
  "ERROR_IDENTIFICADOR",
  "ERROR_OPERADOR",
  "ERROR_PALABRA_RESERVADA",
  "ERROR_LITERAL",
  "OPERADOR_BOOLEANO"
  };
}

