
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 22 11:49:18 ECT 2022
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 18;
  public static final int Llave_c = 25;
  public static final int Op_booleano = 21;
  public static final int Llave_a = 24;
  public static final int If = 7;
  public static final int Void = 32;
  public static final int T_dato = 4;
  public static final int Else = 8;
  public static final int P_RESERVADA = 36;
  public static final int Corchete_c = 27;
  public static final int Corchete_a = 26;
  public static final int Op_DOS_PUNTOS = 34;
  public static final int While = 10;
  public static final int Division = 16;
  public static final int Int = 5;
  public static final int Op_disminucion = 33;
  public static final int Cadena = 6;
  public static final int Parentesis_c = 23;
  public static final int Op_ACCESO = 37;
  public static final int Parentesis_a = 22;
  public static final int For = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Op_atribucion = 19;
  public static final int ERROR = 38;
  public static final int Do = 9;
  public static final int ASIGNACION = 12;
  public static final int Op_logico = 17;
  public static final int PUNTO = 31;
  public static final int Identificador = 29;
  public static final int Resta = 14;
  public static final int Multiplicacion = 15;
  public static final int Op_incremento = 20;
  public static final int Numero = 30;
  public static final int TERMINADOR = 35;
  public static final int Suma = 13;
  public static final int Main = 28;
  public static final int Comillas = 3;
}

