package lexico;

/**
 *
 * @author root
 */
public enum Tokens {
    PALABRA_RESERVADA,
    OPERADOR,
    OPERADOR_IGUAL,
    OPERADOR_ADICION,
    OPERADOR_SUSTRACCION,
    OPERADOR_MULTIPLICACION,
    OPERADOR_DIVISION,
    IDENTIFICADOR,
    NUMERO,
    TERMINADOR,
    OPERADOR_COMA,
    OPERADOR_INCREMENTO,
    OPERADOR_DISMINUCION,
    OPERADOR_MAYOR_IGUAL_QUE,
    OPERADOR_MAYOR_QUE,
    OPERADOR_MENOR_IGUAL_QUE,
    OPERADOR_MENOR_QUE,
    OPERADOR_DIFERENTE_DE,
    OPERADOR_PARENTESIS_ABRIR,
    OPERADOR_PARENTESIS_CERRAR,
    OPERADOR_CORCHETE_ABRIR,
    OPERADOR_CORCHETE_CERRAR,
    OPERADOR_PUNTO,
    OPERADOR_DOS_PUNTOS,
    LITERAL_NUM_ENTERO,
    LITERAL_NUM_FLOTANTE,
    LITERAL_STRING,
    ERROR_IDENTIFICADOR,
    ERROR_LITERAL,
    ERROR
}
