
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 24 13:51:17 ECT 2022
//----------------------------------------------------

package semantico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_Dato = 15;
  public static final int ERROR_IDENTIFICADOR = 38;
  public static final int Llave_c = 33;
  public static final int Llave_a = 32;
  public static final int If = 21;
  public static final int Void = 8;
  public static final int Op_Logico = 26;
  public static final int Else = 22;
  public static final int Op_Incremento = 29;
  public static final int Corchete_c = 35;
  public static final int Corchete_a = 34;
  public static final int Op_Acceso = 9;
  public static final int Op_Relacional = 27;
  public static final int Punto = 4;
  public static final int While = 24;
  public static final int Division = 13;
  public static final int Op_Disminucion = 30;
  public static final int Parentesis_c = 37;
  public static final int Cadena = 20;
  public static final int Parentesis_a = 36;
  public static final int For = 25;
  public static final int EOF = 0;
  public static final int P_coma = 6;
  public static final int DosPuntos = 5;
  public static final int error = 1;
  public static final int Op_Booleano = 31;
  public static final int entero = 16;
  public static final int Do = 23;
  public static final int Identificador = 2;
  public static final int ERROR_LITERAL = 39;
  public static final int Resta = 11;
  public static final int Bool = 19;
  public static final int Multiplicacion = 12;
  public static final int Suma = 10;
  public static final int Main = 7;
  public static final int Igual = 14;
  public static final int decimal = 17;
  public static final int Op_Atribucion = 28;
  public static final int cadena = 18;
  public static final int Comillas = 3;
}

